/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Authentication error code
*/
export enum AuthErrorCode {
    ApiKeyMissing = <any> 'APIKeyMissing',
    InvalidApiKey = <any> 'InvalidAPIKey'
}
