/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Participant } from './participant';

/**
* Information of the created solution
*/
export class CreateSolutionResponse {
    'participant': Participant;
    /**
    * Trial number
    */
    'trialNo': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "participant",
            "baseName": "participant",
            "type": "Participant"
        },
        {
            "name": "trialNo",
            "baseName": "trialNo",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CreateSolutionResponse.attributeTypeMap;
    }
}

