/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Failed to retrieve the solution
*/
export enum GetSolutionError {
    InvalidMatchId = <any> 'InvalidMatchId',
    InvalidParticipantId = <any> 'InvalidParticipantId',
    TrialNotFound = <any> 'TrialNotFound'
}
