/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MatchTrialStatus } from './matchTrialStatus';

/**
* Information of the created Solution
*/
export class MatchTrialResponse {
    /**
    * Trial number
    */
    'trialNo': number;
    'status': MatchTrialStatus;
    /**
    * Creation date and time
    */
    'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "trialNo",
            "baseName": "trialNo",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "MatchTrialStatus"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return MatchTrialResponse.attributeTypeMap;
    }
}

export namespace MatchTrialResponse {
}
