/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Types of trial status.
*/
export enum MatchTrialStatus {
    Evaluating = <any> 'evaluating',
    EvaluatorFailed = <any> 'evaluator_failed',
    ScorerFailed = <any> 'scorer_failed',
    Scoring = <any> 'scoring',
    Success = <any> 'success'
}
