/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ParticipantType } from './participantType';

/**
* Participant information
*/
export class Participant {
    'participantType': ParticipantType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "participantType",
            "baseName": "participantType",
            "type": "ParticipantType"
        }    ];

    static getAttributeTypeMap() {
        return Participant.attributeTypeMap;
    }
}

export namespace Participant {
}
