/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A double-precision floating-point scalar or vector.
*/
export class ScalarOrVector {
    /**
    * A double-precision floating-point vector.
    */
    'vector'?: Array<number>;
    /**
    * A double-precision floating-point scalar value
    */
    'scalar'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "vector",
            "baseName": "vector",
            "type": "Array<number>"
        },
        {
            "name": "scalar",
            "baseName": "scalar",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ScalarOrVector.attributeTypeMap;
    }
}

