/**
 * OptHub REST API
 * OptHubの公開REST APIです。
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ParticipantType } from './participantType';

/**
* 解
*/
export class Solution {
    /**
    * 競技のID
    */
    'matchId': string;
    'participantType': ParticipantType;
    /**
    * 参加者のID
    */
    'participantId': string;
    /**
    * 試行番号
    */
    'trialNo': number;
    /**
    * 解空間の変数
    */
    'variable': object;
    /**
    * 作成日時
    */
    'createdAt': Date;
    /**
    * 作成したユーザのID
    */
    'userId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "matchId",
            "baseName": "matchId",
            "type": "string"
        },
        {
            "name": "participantType",
            "baseName": "participantType",
            "type": "ParticipantType"
        },
        {
            "name": "participantId",
            "baseName": "participantId",
            "type": "string"
        },
        {
            "name": "trialNo",
            "baseName": "trialNo",
            "type": "number"
        },
        {
            "name": "variable",
            "baseName": "variable",
            "type": "object"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Solution.attributeTypeMap;
    }
}

export namespace Solution {
}
